In [20]:
import numpy as np

In [21]:
# activation fun
def sigmoid (x):
    return (1/(1+np.exp(-x)))

In [ ]:
def s_der 

In [22]:
# inputs
input = np.array(
    [
        [1,0,1],
        [1,1,1],
        [0,1,1],
        [0,0,1]

    ]  
)
    

In [23]:
t_output = np.array([[1,1,0,0]]).T
t_output

array([[1],
       [1],
       [0],
       [0]])

In [24]:
t_out = np.array([[1],[1],[0],[0]])

In [25]:
t_out

array([[1],
       [1],
       [0],
       [0]])

In [26]:
weights = 2*np.random.random((3,1)) -1
# weights = np.random.random((3,1)) 
weights

array([[ 0.41851673],
       [-0.91785735],
       [ 0.6710912 ]])

In [27]:
for iter in range (1):
    output = sigmoid (np.dot(input, weights))

In [28]:
np.round(output)
       # [1],
       # [1],
       # [0],
       # [0]


array([[1.],
       [1.],
       [0.],
       [1.]])

In [30]:
output

array([[0.74830789],
       [0.54283241],
       [0.43861962],
       [0.66174745]])